FROM python:3.6-stretch

COPY requirements.txt /opt/requirements.txt

RUN mkdir -p /workdir /opt/tuxeatpi_hotword_kittai/libs

COPY Makefile /opt/Makefile
RUN apt-get update && \
    apt-get install -y --no-install-recommends git gcc python3 libpython3.5 libatlas3-base libportaudio2 swig pulseaudio-utils pulseaudio make g++ python3-dev musl-dev portaudio19-dev swig libatlas-base-dev pulseaudio-utils pulseaudio && \
    apt-get clean && \
    pip install -r /opt/requirements.txt && \
    cd /opt && make dev-build-snowboy && cd / && \
    apt-get -y purge python3-dev musl-dev portaudio19-dev libatlas-base-dev g++ make && apt -y autoremove --purge && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
# Configure pulseaudio
RUN echo enable-shm=no >> /etc/pulse/client.conf
ENV PULSE_SERVER /run/pulse/native


COPY test_requirements.txt /opt/test_requirements.txt
COPY setup.py /opt/setup.py
COPY tuxeatpi_hotword_kittai /opt/tuxeatpi_hotword_kittai
RUN cd /opt && python setup.py install && cd /

WORKDIR /workdir

COPY dialogs /dialogs
COPY intents /intents

COPY misc/docker-pulseaudio-entrypoint.sh /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["tep"]
